algoritmo "Contador com repita e eqnato"
var
     cont: inteiro
inicio
       cont <- 0
       repita
       escreva (cont)
       cont <- cont + 1
       ate (cont>10)
       // Repita funciona com a condicional no final da expressão
       
       enquanto   (cont <= 20) faca
       escreva (cont)
       cont <- cont + 1
       fimenquanto
       // enquanto funcioona com a condicional no inicio da expressão
fimalgoritmo