algoritmo "Somaparametrosreferencia"
var
   X, Y: inteiro
   procedimento Soma(var A , B: inteiro)
   inicio
         A <- A + 1
         B <- B + 2
         Escreval (" Valor de A = ", A)
         Escreval (" Valor de B = ", B)
         Escreval (" A soma de A + B é = ", A+B)
   fimprocedimento
inicio
      X <- 4
      Y <- 8
      Soma (X ,Y)
      Escreval ( " Valor de X = ", X)
      escreval (" Valor de Y = ", Y)
      

fimalgoritmo